
platform :osx, '10.12'
use_frameworks!
install! 'cocoapods', generate_multiple_pod_projects: true

target 'Storage_Example' do
  pod 'SQLiteORM', :path => '../../SQLiteORM'
  pod 'MMapKV', :path => '../../MMapKV'
  pod 'Redisable', :path => '../../Redisable'
  pod 'Storage', :path => '../'

  target 'Storage_Tests' do
    inherit! :search_paths

    
  end
end
